language: node_js
branches:
  only:
  - master
node_js:
  - 'lts/*'
services:
  - docker
script:
  #- npm install pkg -g
  #- npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t reruin/sharelist:latest .
  - docker push reruin/sharelist:latest